### PR TITLE
Group 9: Language-detector // Jessica Ngo & Matthew Panebianco & Sam Braun

### PR DESCRIPTION
**Pull request by JessicaNgo**
Added an extra function to parse a string of words and format it into a list which can be added to LANGUAGES list in languages.py

Group members: 
Jessica Ngo
Matthew Panebianco
Sam Braun

### CODE REVIEW

**Comment by martinzugnoni** [comment]
Guys, we love well commented code. But I think you've commented too much. Actually there're many lines of old code commented which should be removed. Can you please make a clean up? thanks!

**Comment by Metallidog** [comment]
I'd like to suggest that whenever you catch yourself using:

```
for index in range(len(some_list)):
    some_list[index] = .... do something...
```

because the index is important to your "do something"
then use:

```
 for index, item in enumerate(some_list):
    .... do something....
```

This will give you access to the index and item at the same time and is more pythonic

**Comment by JessicaNgo** [comment]
Hey! Thanks for that tip, I did not know :) When you use 

```
for index, item in enumerate(some_list):
```

what does item refer to?

**Comment by Metallidog** [comment]
```
for index, item in enumerate(['a', 'b', 'c', 'd']):
    print (index, item) 
0 a
1 b
2 c
3 d
```

Index is the index of the list and item is the item at that index.

**Pull request closed without merging**
