### PR TITLE
Group 4 - Solution for Language Detector

### PR DESCRIPTION
**Pull request by bdauer**
Sean, Anubhav, Ben

### CODE REVIEW

**Comment by gkarp** [comment]
Hey guys, I've started reviewing your code. It looks pretty good so far. Will post questions as I find them:

create_set_from_text(text)
- Not saying what you did is wrong, but why did you decide not to use try and excepts? Is it because you cannot differentiate between different causes of Value Error?

**Comment by gkarp** [comment]
Your code is very functional ;) very well done in that regard. Do you mind explaining why you decided to compartmentalize both creating a set from common words and creating a set from the text? Since these are both inputs required for the program to run, I think that it would make sense to validate them in one function. But again, just a suggestion / question. 

Done Reviewing.

**Comment by an00bhav** [comment]
@gkarp The string inside ValueError will be able to differentiate on what is causing the ValueError. Regarding try/catch vs raise, create_set_from_text(text) is kind of the API we have wrote and detect_language is the code that uses our API. Now my API will raise error for the people using the API, and they will decide how to handle the exceptions. So technically detect_language should be using try/except block to catch error raised by my API. I hope I am clear in my explanation.

And yes you are write,we could have use one function to validate the input, and I wanted to implement something like is_input_valid and is_languages_valid, but just couldn't get the time. I have written test_cases for all my API, so had to write them for these two functions too. 

Thanks for the review.

**Comment by santiagobasulto** [comment]
Good stuff guys, closing it now.

**Pull request closed without merging**
